## Data Pre-processing

In [1]:
#https://towardsdatascience.com/introduction-to-data-preprocessing-in-machine-learning-a9fa83a5dc9d

#https://machinelearningmastery.com/handle-missing-data-python/

#https://towardsdatascience.com/data-cleaning-with-python-and-pandas-detecting-missing-values-3e9c6ebcf78b

#https://towardsdatascience.com/the-tale-of-missing-values-in-python-c96beb0e8a9d

#https://www.kaggle.com/chepkoyallan/data-preprocessing-for-machine-learning-projects

#https://towardsdatascience.com/data-preprocessing-in-python-b52b652e37d5

In [1]:
import os

In [2]:
pwd

'C:\\Users\\HP\\Udemy python\\Data Preprocesssing,Feature Selection'

In [3]:
os.getcwd()

'C:\\Users\\HP\\Udemy python\\Data Preprocesssing,Feature Selection'

In [4]:
os.chdir('C:\\Users\\HP\\Desktop')

In [35]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = pd.read_csv('Data.csv')
data

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

### Placing independent(input) variables in 'x' & dependent(outpur or target) variable in 'y' 

In [36]:
X = data.iloc[:,:-1].values         # .values used here return a numpy representation of the dataframe
y = data .iloc[:,3].values          # only the values in the dataframe will be returned, the axes labels will be removed.+
X,y

(array([['France', 44.0, 72000.0],
        ['Spain', 27.0, 48000.0],
        ['Germany', 30.0, 54000.0],
        ['Spain', 38.0, 61000.0],
        ['Germany', 40.0, nan],
        ['France', 35.0, 58000.0],
        ['Spain', nan, 52000.0],
        ['France', 48.0, 79000.0],
        ['Germany', 50.0, 83000.0],
        ['France', 37.0, 67000.0]], dtype=object),
 array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
       dtype=object))

### Taking care of missing values

In [37]:
# filling missing values is essential and should be done before encoding categorical features.

print(data.isnull().sum())

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64


In [38]:
#df['A'].fillna(value = df['A'].mean()) or
#df.fillna(value = df['C'].mean())

#Use only one method at a time don't use two
# Method-1 : By using sklearn package

from sklearn.preprocessing import Imputer
imputer = Imputer(missing_values = 'NaN',strategy = 'mean', axis = 0)
imputer = imputer.fit(X[:,1:3]) # mention the index position of columns with missing values 
X[:,1:3] = imputer.transform(X[:,1:3])

In [39]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [40]:
# Method-2 : By using pandas 
# since our data is in pandas dataframe 
df = data.fillna(value = data[['Age','Salary']].mean())
df

Country        Age        Salary Purchased
0   France  44.000000  72000.000000        No
1    Spain  27.000000  48000.000000       Yes
2  Germany  30.000000  54000.000000        No
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000        No
9   France  37.000000  67000.000000       Yes

In [9]:
X = df.iloc[:,:-1].values
y = df.iloc[:,3].values
X,y

(array([['France', 44.0, 72000.0],
        ['Spain', 27.0, 48000.0],
        ['Germany', 30.0, 54000.0],
        ['Spain', 38.0, 61000.0],
        ['Germany', 40.0, 63777.77777777778],
        ['France', 35.0, 58000.0],
        ['Spain', 38.77777777777778, 52000.0],
        ['France', 48.0, 79000.0],
        ['Germany', 50.0, 83000.0],
        ['France', 37.0, 67000.0]], dtype=object),
 array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
       dtype=object))

### Encoding categorical data

In [41]:
#https://towardsdatascience.com/encoding-categorical-features-21a2651a065c
#https://pbpython.com/categorical-encoding.html


from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
#apply this LabelEncoder() object with fit_transform method on categorical column of matrix X but not the whole matrix of X
#
labelencoder_X.fit_transform(X[:,0])
#output shows ten values of the first column of matrix X after encoding

array([0, 2, 1, 2, 1, 0, 2, 0, 1, 0], dtype=int64)

In [42]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [43]:
X[:,0] = labelencoder_X.fit_transform(X[:,0])

In [44]:
X
# after encoding it shows categorical values of first column of X into numeric values
# France is '0', Spain is '2', Germany is '1'

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [45]:
pd.DataFrame(X)

0        1        2
0  0       44    72000
1  2       27    48000
2  1       30    54000
3  2       38    61000
4  1       40  63777.8
5  0       35    58000
6  2  38.7778    52000
7  0       48    79000
8  1       50    83000
9  0       37    67000

In [46]:
# However do u suspect any problem that could happen?
# The problem is still the same,ML models are based on equations and that's good that v replaced the text by numbers so that we 
# can include the numbers in the equations 
# However since 1 is > 0 and 2 is > 1 the equations in the model think that 'Spain' has a higher value than 'Germany & France', 
# and 'Germany' has higher value than 'France' and that's not the case these('Spain','Germany & France') r actually three
# categories nd there is no relation order between the three.
# We cannot compare or say that Spain is  > Germany&France , Germany is > France
# So We have to prevent the ML equatios from thinking that Germany is > France & Spain is > Geramny
# To prevent this we're going to use what r called "Dummy Variables"
# That means instead of having 1 column here v r going to have 3 columns,i.e,
#(we're going to have a no.of columns equal to the no.of categories) 

#with 'OneHotEncoder' library we can create dummy variables

In [47]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
labelencoder_X = LabelEncoder()
X[:,0] = labelencoder_X.fit_transform(X[:,0])
onehotencoder = OneHotEncoder(categorical_features=[0]) #here v specifying the index position of categorical column
X = onehotencoder.fit_transform(X).toarray()
X

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.40000000e+01,
        7.20000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 2.70000000e+01,
        4.80000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 3.00000000e+01,
        5.40000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.80000000e+01,
        6.10000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 4.00000000e+01,
        6.37777778e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.50000000e+01,
        5.80000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.87777778e+01,
        5.20000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.80000000e+01,
        7.90000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 5.00000000e+01,
        8.30000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.70000000e+01,
        6.70000000e+04]])

In [54]:
X = pd.DataFrame(X)
X.round(0)

0    1    2     3        4
0  1.0  0.0  0.0  44.0  72000.0
1  0.0  0.0  1.0  27.0  48000.0
2  0.0  1.0  0.0  30.0  54000.0
3  0.0  0.0  1.0  38.0  61000.0
4  0.0  1.0  0.0  40.0  63778.0
5  1.0  0.0  0.0  35.0  58000.0
6  0.0  0.0  1.0  39.0  52000.0
7  1.0  0.0  0.0  48.0  79000.0
8  0.0  1.0  0.0  50.0  83000.0
9  1.0  0.0  0.0  37.0  67000.0

In [49]:
# Here the first column 'Country' was replaced by three columns (u can c by comparing it with original dataframe) 
# the 'Age' & 'Salary' column remains the same
# What we are r seeing is that 1st column corresponds to 'France', 2nd column corresponds to 'Germany', 3rd to 'Spain'
# For example take the 1st line(row)that hasn't take 0 is the country France, since the 1st obsevation is France(in original X)
# than that means the 1st column here is going to be 1 because this corresponds to the France column,then since the 2nd column
# is Germany then its going to b 0 here because 1st observation is France not Germany ,3rd column here is Spain and it's 0
# because the 1st observation is France and not Spain

#this is how u encode dummy variables by making sure that the ML models don't attribute in-order into the categorical variables 

In [55]:
# Now lets take care of second varible i.e, target variable(Purchased)
# We don't have to use OneHotEncoder we'll just need to use LabelEncoder because since this is the dependent variable the ML 
# model will know that it's a category and there is no order between the two

labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1], dtype=int64)

### Splitting the data into Training set and Test set 

In [57]:
#https://scikit-learn.org/stable/modules/preprocessing.html
#https://www.geeksforgeeks.org/ml-feature-scaling-part-2/


from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 0)

In [65]:
X_train

0    1    2          3             4
4  0.0  1.0  0.0  40.000000  63777.777778
9  1.0  0.0  0.0  37.000000  67000.000000
1  0.0  0.0  1.0  27.000000  48000.000000
6  0.0  0.0  1.0  38.777778  52000.000000
7  1.0  0.0  0.0  48.000000  79000.000000
3  0.0  0.0  1.0  38.000000  61000.000000
0  1.0  0.0  0.0  44.000000  72000.000000
5  1.0  0.0  0.0  35.000000  58000.000000

### Feature Scaling

In [66]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)



#when u are applying your standard scaler object to your training set u have to fit the object of the training set and then
#transform it, and when coming to test set we only transform and don't fit the object b'cause it's already fitted to the 
#training set.

#"fit" helps in fitting the StandardScaler() object to the matrix and "transform" helps in standardising the matrix

# Do v need to fit and transform the dummy variables ?
# As v can see dummy variables takes values either 0 or 1,so do v need to scale that because it seems to be already scaled
# Google it!
# It depends on the context , on how much u want to keep interpretation in your models.
# Because if we scale this it'll b good because everything will be on the same scale and it's good for predictions 


# Do we need to apply Feature Scaling to y (y_train,y_test) ?
# As u can see the dependend variable y  is categorical it takes only two values 0,1
# we don't need to apply feature scaling because it's  classification problem with categorical dependent variable.
# But u will see that for regression when the dependent variable y has huge range of values we'll go for feature scaling
#  y_train = sc_y.fit_transform(y_train)
#  y_test = sc_y.transform(y_test)

In [68]:
pd.DataFrame(X_train)

0         1         2         3         4
0 -1.0  2.645751 -0.774597  0.263068  0.123815
1  1.0 -0.377964 -0.774597 -0.253501  0.461756
2 -1.0 -0.377964  1.290994 -1.975398 -1.530933
3 -1.0 -0.377964  1.290994  0.052614 -1.111420
4  1.0 -0.377964 -0.774597  1.640585  1.720297
5 -1.0 -0.377964  1.290994 -0.081312 -0.167514
6  1.0 -0.377964 -0.774597  0.951826  0.986148
7  1.0 -0.377964 -0.774597 -0.597881 -0.482149